// Generated by bnh-backend/scripts/export_openapi.py. Do not edit.

export type AccountCreate = {
  "name": string;
  "email": string;
  "initial_password": string;
};

export type AttachmentAccess = {
  "id": string;
  "requisition_id": string;
  "filename": string;
  "media_type": string;
  "validation_state": string;
};

export type BankDetails = {
  "bank_name": string;
  "account_number": string;
  "account_name": string;
};

export type CapabilityPage = {
  "items": Array<CapabilityView>;
  "total": number;
  "limit": number;
  "offset": number;
};

export type CapabilityView = {
  "requisition_id": string;
  "actions": Array<string>;
  "read_only": boolean;
};

export type CreateVendor = {
  "entity_id": string;
  "data": VendorData;
};

export type DepartmentInput = {
  "name": string;
  "code"?: string;
  "entity_id": string;
};

export type DirectoryUpdate = {
  "name"?: string | null;
  "active"?: boolean | null;
};

export type DirectoryView = {
  "id": string;
  "name": string;
  "code": string;
  "active": boolean;
};

export type EntityInput = {
  "name": string;
  "code"?: string;
  "kind"?: "holding" | "subsidiary";
};

export type EntityItem = {
  "id": string;
  "name": string;
  "code": string;
  "active": boolean;
  "kind": string;
};

export type HTTPValidationError = {
  "detail"?: Array<ValidationError>;
};

export type Health = {
  "status": string;
};

export type Item = {
  "id": string;
  "name": string;
  "code": string;
  "active": boolean;
};

export type Login = {
  "email": string;
  "password": string;
};

export type MembershipInput = {
  "identity_id": string;
  "entity_id": string;
  "department_id": string;
};

export type MembershipState = {
  "active": boolean;
};

export type MembershipView = {
  "entity_id": string;
  "entity_name": string;
  "department_id": string;
  "department_name": string;
};

export type Message = {
  "message": string;
};

export type OfficeInput = {
  "identity_id": string;
  "entity_id": string;
  "department_id"?: string | null;
  "role": "hod" | "chief_of_staff" | "md" | "secretary" | "chairman";
  "authorisation_reference": string;
  "valid_from"?: string;
  "valid_until"?: string | null;
};

export type OfficeView = {
  "id": string;
  "identity_id": string;
  "entity_id": string;
  "department_id": string | null;
  "role": string;
  "active": boolean;
  "valid_from": string;
  "valid_until": string | null;
  "authorisation_reference": string;
};

export type Reauthenticate = {
  "password": string;
};

export type Recover = {
  "token": string;
  "password": string;
};

export type ReviewInput = {
  "identity_id": string;
  "entity_id": string;
  "active"?: boolean;
};

export type StaffInput = {
  "name": string;
  "email": string;
  "initial_password": string;
};

export type StaffItem = {
  "id": string;
  "name": string;
  "email": string;
  "active": boolean;
};

export type StaffView = {
  "id": string;
  "name": string;
  "email": string;
  "active": boolean;
};

export type UpdateVendor = {
  "expected_version": number;
  "data": VendorData;
};

export type UserView = {
  "id": string;
  "account_id": string;
  "name": string;
  "email": string;
  "permissions": Array<string>;
  "read_only"?: boolean;
};

export type ValidationError = {
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
  "input"?: unknown;
  "ctx"?: Record<string, unknown>;
};

export type VendorData = {
  "name": string;
  "contact_person"?: string;
  "phones"?: Array<string>;
  "email"?: string | null;
  "address"?: string;
  "registration_id"?: string;
  "bank"?: BankDetails | null;
};

export type VendorPage = {
  "items": Array<VendorSummary>;
  "total": number;
  "limit": number;
  "offset": number;
};

export type VendorSummary = {
  "id": string;
  "entity_id": string;
  "version": number;
  "name": string;
  "registration_id": string;
  "bank_details_state": "unknown" | "supplied" | "restricted";
  "verification"?: "not_verified";
};

export type VendorView = {
  "id": string;
  "entity_id": string;
  "version": number;
  "name": string;
  "registration_id": string;
  "bank_details_state": "unknown" | "supplied" | "restricted";
  "verification"?: "not_verified";
  "can_update": boolean;
  "version_id": string;
  "data": VendorData;
  "beneficiary_version_id": string | null;
};
