// Generated by bnh-backend/scripts/export_openapi.py. Do not edit.

export type AccountCreate = {
  "name": string;
  "email": string;
  "initial_password": string;
};

export type AccountLink = {
  "token": string;
};

export type AccountMembership = {
  "company": string;
  "department": string;
  "active": boolean;
};

export type AccountOffice = {
  "company": string;
  "role": string;
};

export type AccountProfile = {
  "name": string;
  "email": string;
  "read_only": boolean;
  "memberships": Array<AccountMembership>;
  "offices": Array<AccountOffice>;
};

export type AttachmentAccess = {
  "id": string;
  "requisition_id": string;
  "filename": string;
  "media_type": string;
  "validation_state": string;
};

export type AttachmentPage = {
  "items": Array<AttachmentView>;
  "request_version": number;
  "uploads_enabled": boolean;
  "max_bytes": number;
  "max_count": number;
};

export type AttachmentView = {
  "id": string;
  "filename": string;
  "media_type": string;
  "byte_size": number;
  "digest": string;
  "frozen": boolean;
  "validation_state": string;
  "malware_scan"?: "not_performed";
};

export type AuditPage = {
  "items": Array<AuditRow>;
  "total": number;
  "limit": number;
  "offset": number;
  "before": string;
};

export type AuditRow = {
  "id": string;
  "action": string;
  "at": string;
  "actor_id": string | null;
  "actor_name": string;
  "company": string | null;
  "outcome": string;
  "request_id"?: string | null;
  "reference"?: string | null;
  "attachment_id"?: string | null;
  "attachment_filename"?: string | null;
  "revision_id"?: string | null;
  "content_digest"?: string | null;
};

export type AuthorityRow = {
  "requester": string;
  "authorities": Array<string>;
};

export type BankDetails = {
  "bank_name": string;
  "account_number": string;
  "account_name": string;
};

export type BoardCase = {
  "request": RequestView;
  "records": Array<ResolutionView>;
  "available_actions": Array<string>;
  "blocker"?: string | null;
  "uploads_enabled": boolean;
};

export type BoardIntent = {
  "expected_version": number;
  "action": "board_submit" | "board_confirm" | "board_return";
  "reason"?: string;
};

export type BoardSignedAction = {
  "expected_version": number;
  "action": "board_submit" | "board_confirm" | "board_return";
  "reason"?: string;
  "challenge_id": string;
  "idempotency_key": string;
  "signer_name": string;
  "consent": true;
  "strokes": Array<Array<Point>>;
};

export type CapabilityPage = {
  "items": Array<CapabilityView>;
  "total": number;
  "limit": number;
  "offset": number;
};

export type CapabilityView = {
  "requisition_id": string;
  "actions": Array<string>;
  "read_only": boolean;
};

export type ChallengeView = {
  "id": string;
  "content_digest": string;
  "expires_at": string;
  "statement": string;
  "total": string;
  "authority"?: string | null;
  "routing_explanation"?: string | null;
};

export type ChangePassword = {
  "current_password": string;
  "new_password": string;
};

export type Content = {
  "vendor"?: VendorInfo;
  "description"?: string;
  "location"?: string;
  "start_date"?: string | null;
  "completion_date"?: string | null;
  "payment_terms"?: string;
  "warranty"?: string;
  "currency"?: "NGN";
  "lines"?: Array<CostLine>;
};

export type CostLine = {
  "description": string;
  "quantity": string;
  "unit_price": string;
};

export type CreateRequest = {
  "entity_id": string;
  "creation_key": string;
  "content": Content;
  "vendor_selection"?: VendorSelection | null;
};

export type CreateVendor = {
  "entity_id": string;
  "data": VendorData;
};

export type DashboardActivity = {
  "id": string;
  "request_id": string;
  "reference": string;
  "label": string;
  "at": string;
};

export type DashboardCount = {
  "state": string;
  "count": number;
};

export type DashboardView = {
  "counts": Array<DashboardCount>;
  "total": number;
  "own_requests": number;
  "can_create": boolean;
  "can_access_approval_inbox": boolean;
  "tasks": Page;
  "recent_requests": Page;
  "activity": Array<DashboardActivity>;
  "refreshed_at": string;
};

export type DepartmentInput = {
  "name": string;
  "code"?: string;
  "entity_id": string;
};

export type DirectoryUpdate = {
  "expected_version"?: string | null;
  "name"?: string | null;
  "active"?: boolean | null;
};

export type DirectoryView = {
  "id": string;
  "name": string;
  "code": string;
  "active": boolean;
};

export type EntityInput = {
  "name": string;
  "code"?: string;
  "kind"?: "holding" | "subsidiary";
};

export type EntityItem = {
  "id": string;
  "name": string;
  "code": string;
  "active": boolean;
  "kind": string;
};

export type ForgotPassword = {
  "email": string;
};

export type HTTPValidationError = {
  "detail"?: Array<ValidationError>;
};

export type Health = {
  "status": string;
};

export type HistoryEntry = {
  "id": string;
  "type": string;
  "at": string;
  "actor": string;
  "actor_id"?: string | null;
  "revision"?: number | null;
  "reason"?: string | null;
  "authority"?: string | null;
  "routing_explanation"?: string | null;
  "policy_version"?: string | null;
  "signature_id"?: string | null;
  "digest"?: string | null;
  "resolution_id"?: string | null;
  "resolution_number"?: number | null;
  "resolution_reference"?: string | null;
  "meeting_date"?: string | null;
  "evidence_id"?: string | null;
  "evidence_filename"?: string | null;
};

export type HistoryPage = {
  "items": Array<HistoryEntry>;
  "total": number;
  "limit": number;
  "offset": number;
};

export type Intent = {
  "expected_version": number;
  "action": "submit" | "approve" | "reject" | "return";
  "reason"?: string;
};

export type InvitationView = {
  "identity_id": string;
  "email": string;
  "status"?: "invited";
};

export type InviteAccount = {
  "name": string;
  "email": string;
};

export type Item = {
  "id": string;
  "name": string;
  "code": string;
  "active": boolean;
};

export type LinkStatus = {
  "purpose": "reset" | "activate";
};

export type Login = {
  "email": string;
  "password": string;
};

export type MembershipInput = {
  "identity_id": string;
  "entity_id": string;
  "department_id": string;
};

export type MembershipState = {
  "active": boolean;
};

export type MembershipView = {
  "entity_id": string;
  "entity_name": string;
  "department_id": string;
  "department_name": string;
};

export type Message = {
  "message": string;
};

export type NamedOffice = {
  "id": string;
  "identity_id": string;
  "entity_id": string;
  "department_id": string | null;
  "role": string;
  "active": boolean;
  "valid_from": string;
  "valid_until": string | null;
  "authorisation_reference": string;
  "holder_name": string;
  "department_name": string | null;
  "status": "active" | "revoked" | "expired" | "scheduled" | "blocked";
  "reason": string;
};

export type NextAction = {
  "label": string;
  "actor_name"?: string | null;
  "blocked_reason"?: string | null;
};

export type NotificationPage = {
  "items": Array<NotificationView>;
  "total": number;
  "unread_total": number;
  "limit": number;
  "offset": number;
  "email_enabled": boolean;
};

export type NotificationView = {
  "id": string;
  "event_id": string;
  "title": string;
  "message": string;
  "reference": string;
  "href": string;
  "created_at": string;
  "read_at": string | null;
  "email_status": string;
  "attempts": number;
  "last_error": string | null;
};

export type OfficeInput = {
  "identity_id": string;
  "entity_id": string;
  "department_id"?: string | null;
  "role": "hod" | "chief_of_staff" | "md" | "secretary" | "chairman";
  "authorisation_reference": string;
  "valid_from"?: string;
  "valid_until"?: string | null;
};

export type OfficeView = {
  "id": string;
  "identity_id": string;
  "entity_id": string;
  "department_id": string | null;
  "role": string;
  "active": boolean;
  "valid_from": string;
  "valid_until": string | null;
  "authorisation_reference": string;
};

export type OrganisationEdit = {
  "expected_version": string;
  "name"?: string | null;
  "active"?: boolean | null;
};

export type OrganisationRecord = {
  "id": string;
  "name": string;
  "code": string;
  "active": boolean;
  "version": string;
  "kind"?: string | null;
  "entity_id"?: string | null;
};

export type OrganisationWorkspace = {
  "entities": Array<OrganisationRecord>;
  "selected_entity": string | null;
  "departments": Array<OrganisationRecord>;
  "offices": Array<NamedOffice>;
  "authority_gaps": Array<string>;
  "bands": Array<string>;
  "matrix": Array<AuthorityRow>;
  "rules": Array<string>;
};

export type Page = {
  "items": Array<Summary>;
  "total": number;
  "limit": number;
  "offset": number;
};

export type Point = {
  "x": number;
  "y": number;
};

export type Reauthenticate = {
  "password": string;
};

export type Recover = {
  "token": string;
  "password": string;
};

export type RequestView = {
  "id": string;
  "reference": string;
  "entity_id": string;
  "requester_name": string;
  "entity_name": string;
  "department_name": string;
  "state": string;
  "version": number;
  "total": string;
  "created_at": string;
  "required_authority": string | null;
  "routing_explanation": string | null;
  "submission_blocker"?: string | null;
  "decision_blocker"?: string | null;
  "viewing_revision"?: number | null;
  "content": Content;
  "available_actions": Array<string>;
  "revision_number": number;
  "redacted_fields"?: Array<string>;
  "next_action"?: NextAction | null;
  "history": Array<Record<string, unknown>>;
};

export type ResolutionData = {
  "meeting_date"?: string | null;
  "board_name"?: string;
  "reference"?: string;
  "decision_text"?: string;
  "outcome"?: "APPROVE" | "REJECT" | "DEFER" | "CONDITIONAL_APPROVE";
  "authorised_amount"?: string | null;
  "currency"?: "NGN";
  "correction_summary"?: string;
  "conditions"?: string;
  "attendance"?: string;
  "quorum_attested"?: boolean;
  "quorum_basis"?: string;
  "evidence_type"?: "resolution" | "minutes_extract";
};

export type ResolutionView = {
  "id": string;
  "number": number;
  "predecessor_id": string | null;
  "kind": string;
  "data": ResolutionData;
  "status": string;
  "recorded_at": string;
  "submitted_at": string | null;
  "secretary_name": string | null;
  "chairman_name": string | null;
  "decided_at": string | null;
  "return_reason": string | null;
  "evidence": AttachmentView | null;
};

export type ReviewInput = {
  "identity_id": string;
  "entity_id": string;
  "active"?: boolean;
};

export type SaveResolution = {
  "expected_version": number;
  "idempotency_key": string;
  "data": ResolutionData;
};

export type SessionPage = {
  "items": Array<SessionView>;
  "total": number;
  "limit": number;
  "offset": number;
};

export type SessionView = {
  "id": string;
  "created_at": string;
  "expires_at": string;
  "current": boolean;
};

export type SignedAction = {
  "expected_version": number;
  "action": "submit" | "approve" | "reject" | "return";
  "reason"?: string;
  "challenge_id": string;
  "idempotency_key": string;
  "signer_name": string;
  "consent": true;
  "strokes": Array<Array<Point>>;
};

export type StaffDetail = {
  "id": string;
  "name": string;
  "email": string;
  "status": "active" | "invited" | "disabled";
  "read_only": boolean;
  "version": string;
  "memberships": Array<StaffMembership>;
  "offices": Array<OfficeView>;
  "actions": Array<string>;
};

export type StaffEdit = {
  "expected_version": string;
  "name": string;
};

export type StaffInput = {
  "name": string;
  "email": string;
  "initial_password": string;
};

export type StaffItem = {
  "id": string;
  "name": string;
  "email": string;
  "active": boolean;
};

export type StaffMembership = {
  "entity_id": string;
  "entity_name": string;
  "department_id": string;
  "department_name": string;
  "active": boolean;
  "scope_active": boolean;
};

export type StaffMembershipSet = {
  "expected_version": string;
  "identity_id": string;
  "entity_id": string;
  "department_id": string;
};

export type StaffMembershipState = {
  "expected_version": string;
  "active": boolean;
};

export type StaffOfficeSet = {
  "expected_version": string;
  "identity_id": string;
  "entity_id": string;
  "department_id"?: string | null;
  "role": "hod" | "chief_of_staff" | "md" | "secretary" | "chairman";
  "authorisation_reference": string;
  "valid_from"?: string;
  "valid_until"?: string | null;
};

export type StaffOption = {
  "id": string;
  "name": string;
  "entity_id"?: string | null;
};

export type StaffOptions = {
  "entities": Array<StaffOption>;
  "departments": Array<StaffOption>;
  "email_enabled": boolean;
};

export type StaffPage = {
  "items": Array<StaffSummary>;
  "total": number;
  "limit": number;
  "offset": number;
};

export type StaffState = {
  "expected_version": string;
  "active": boolean;
};

export type StaffSummary = {
  "id": string;
  "name": string;
  "email": string;
  "status": "active" | "invited" | "disabled";
  "read_only": boolean;
};

export type StaffVersion = {
  "expected_version": string;
};

export type StaffView = {
  "id": string;
  "name": string;
  "email": string;
  "active": boolean;
};

export type StartRevision = {
  "expected_version": number;
  "idempotency_key": string;
};

export type Summary = {
  "id": string;
  "reference": string;
  "state": string;
  "total": string;
  "description": string;
  "created_at": string;
  "requester_name": string;
  "required_authority": string | null;
  "department_name"?: string;
  "entity_name"?: string;
  "vendor_name"?: string;
};

export type UpdateRequest = {
  "expected_version": number;
  "content": Content;
  "vendor_selection"?: VendorSelection | null;
};

export type UpdateVendor = {
  "expected_version": number;
  "data": VendorData;
};

export type UserView = {
  "id": string;
  "account_id": string;
  "name": string;
  "email": string;
  "permissions": Array<string>;
  "read_only"?: boolean;
  "can_access_approval_inbox"?: boolean;
};

export type ValidationError = {
  "loc": Array<string | number>;
  "msg": string;
  "type": string;
  "input"?: unknown;
  "ctx"?: Record<string, unknown>;
};

export type VendorData = {
  "name": string;
  "contact_person"?: string;
  "phones"?: Array<string>;
  "email"?: string | null;
  "address"?: string;
  "registration_id"?: string;
  "bank"?: BankDetails | null;
};

export type VendorInfo = {
  "name"?: string;
  "contact_person"?: string;
  "phone"?: string;
  "email"?: string;
  "address"?: string;
  "registration_id"?: string;
  "bank_name"?: string;
  "account_number"?: string;
  "account_name"?: string;
};

export type VendorPage = {
  "items": Array<VendorSummary>;
  "total": number;
  "limit": number;
  "offset": number;
};

export type VendorSelection = {
  "id": string;
  "expected_version": number;
};

export type VendorSummary = {
  "id": string;
  "entity_id": string;
  "version": number;
  "name": string;
  "registration_id": string;
  "bank_details_state": "unknown" | "supplied" | "restricted";
  "verification"?: "not_verified";
};

export type VendorView = {
  "id": string;
  "entity_id": string;
  "version": number;
  "name": string;
  "registration_id": string;
  "bank_details_state": "unknown" | "supplied" | "restricted";
  "verification"?: "not_verified";
  "can_update": boolean;
  "version_id": string;
  "data": VendorData;
  "beneficiary_version_id": string | null;
};
